# -*- coding: utf-8 -*-
"""customer_churn_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltegBhZEvRNFIYP2jz_QCz5apxwsZah9
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.describe()
df.isnull().sum()
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df.head()

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='Churn', data=df)
plt.show()

df.corr(numeric_only=True)

df.to_csv('cleaned_churn_data.csv', index=False)

from sklearn.model_selection import train_test_split

X = df.drop('Churn', axis=1)
y = df['Churn']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))